/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotpassRouteImport } from './routes/forgotpass'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUploadRouteImport } from './routes/_authed/upload'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthGoogleRouteImport } from './routes/Auth.google'
import { Route as AuthCallbackRouteImport } from './routes/Auth.callback'
import { Route as AuthedUserProfileRouteImport } from './routes/_authed/user/profile'
import { Route as AuthedUserCartRouteImport } from './routes/_authed/user/cart'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpassRoute = ForgotpassRouteImport.update({
  id: '/forgotpass',
  path: '/forgotpass',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUploadRoute = AuthedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/Auth/google',
  path: '/Auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/Auth/callback',
  path: '/Auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserProfileRoute = AuthedUserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserCartRoute = AuthedUserCartRouteImport.update({
  id: '/user/cart',
  path: '/user/cart',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/forgotpass': typeof ForgotpassRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/Auth/callback': typeof AuthCallbackRoute
  '/Auth/google': typeof AuthGoogleRoute
  '/products': typeof AuthedProductsRoute
  '/upload': typeof AuthedUploadRoute
  '/user/cart': typeof AuthedUserCartRoute
  '/user/profile': typeof AuthedUserProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/forgotpass': typeof ForgotpassRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/Auth/callback': typeof AuthCallbackRoute
  '/Auth/google': typeof AuthGoogleRoute
  '/products': typeof AuthedProductsRoute
  '/upload': typeof AuthedUploadRoute
  '/user/cart': typeof AuthedUserCartRoute
  '/user/profile': typeof AuthedUserProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/forgotpass': typeof ForgotpassRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/Auth/callback': typeof AuthCallbackRoute
  '/Auth/google': typeof AuthGoogleRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/upload': typeof AuthedUploadRoute
  '/_authed/user/cart': typeof AuthedUserCartRoute
  '/_authed/user/profile': typeof AuthedUserProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feedback'
    | '/forgotpass'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/signup'
    | '/Auth/callback'
    | '/Auth/google'
    | '/products'
    | '/upload'
    | '/user/cart'
    | '/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/feedback'
    | '/forgotpass'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/signup'
    | '/Auth/callback'
    | '/Auth/google'
    | '/products'
    | '/upload'
    | '/user/cart'
    | '/user/profile'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/feedback'
    | '/forgotpass'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/signup'
    | '/Auth/callback'
    | '/Auth/google'
    | '/_authed/products'
    | '/_authed/upload'
    | '/_authed/user/cart'
    | '/_authed/user/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotpassRoute: typeof ForgotpassRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotpass': {
      id: '/forgotpass'
      path: '/forgotpass'
      fullPath: '/forgotpass'
      preLoaderRoute: typeof ForgotpassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/upload': {
      id: '/_authed/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthedUploadRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/Auth/google': {
      id: '/Auth/google'
      path: '/Auth/google'
      fullPath: '/Auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/callback': {
      id: '/Auth/callback'
      path: '/Auth/callback'
      fullPath: '/Auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/user/profile': {
      id: '/_authed/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof AuthedUserProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/user/cart': {
      id: '/_authed/user/cart'
      path: '/user/cart'
      fullPath: '/user/cart'
      preLoaderRoute: typeof AuthedUserCartRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedUploadRoute: typeof AuthedUploadRoute
  AuthedUserCartRoute: typeof AuthedUserCartRoute
  AuthedUserProfileRoute: typeof AuthedUserProfileRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedUploadRoute: AuthedUploadRoute,
  AuthedUserCartRoute: AuthedUserCartRoute,
  AuthedUserProfileRoute: AuthedUserProfileRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotpassRoute: ForgotpassRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGoogleRoute: AuthGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
